import { Pencil } from 'lucide-react'
import { useEffect } from 'react'
import { useNavigate } from 'react-router-dom'

import { Button } from '@/components/ui/button'
import { RoadmapFlow } from '@/components/RoadmapFlow'
import { useRoadmap } from '@/context/RoadmapContext'

export default function Roadmap() {
  const navigate = useNavigate()
  const { selectedStrategy, sandboxId, roadmap } = useRoadmap()

  useEffect(() => {
    if (!selectedStrategy) {
      navigate('/start')
    }
  }, [selectedStrategy, navigate])

  const weeks = roadmap?.weeks || []
  const fallbackResources = [
    {
      type: 'video',
      title: 'General intro',
      url: 'https://www.youtube.com',
      summary: 'High-level overview to get started.',
    },
  ]

  return (
    <div className="flex min-h-screen bg-black text-white">
      <div className="w-64 space-y-8 border-r border-gray-800 bg-[#0f0f18] p-6">
        <div className="flex items-center gap-3">
          <div className="h-12 w-12 rounded-lg bg-gradient-to-br from-purple-500 to-pink-500" />
          <div>
            <div className="font-bold">PolyPath</div>
            <div className="text-sm text-gray-400">AI Learning Architect</div>
          </div>
        </div>

        <nav className="space-y-4 text-sm">
          <div className="text-gray-500">Configuration</div>
          <div className="text-gray-500">Selection</div>
          <div className="font-bold text-purple-400">Realization</div>
        </nav>
      </div>

      <div className="flex-1 p-12">
        <div className="mx-auto flex max-w-4xl flex-col space-y-12">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-4xl font-bold">
                {roadmap?.title || selectedStrategy?.name || 'Learning Roadmap'}
              </h1>
              <div className="mt-2 text-lg text-green-400">
                ● VERIFIED SOURCE: LIVE WEB {sandboxId ? `| Sandbox: ${sandboxId}` : ''}
              </div>
              {roadmap?.summary && <p className="mt-2 max-w-3xl text-gray-400">{roadmap.summary}</p>}
            </div>
          </div>

          <RoadmapFlow title={roadmap?.title || selectedStrategy?.name || 'Roadmap'} weeks={weeks} />

          <div className="space-y-8">
            {(weeks.length ? weeks : Array.from({ length: selectedStrategy?.weeks || 3 }, (_: number, i: number) => ({ week: i + 1 }))).map(
              (week: any, idx: number) => (
                <div key={week.week ?? idx} className="border-b border-gray-800 pb-8">
                  <h3 className="mb-6 text-xl font-semibold">
                    WEEK {week.week || idx + 1} {week.focus ? `— ${week.focus}` : ''}
                  </h3>
                  {week.goals && (
                    <ul className="mb-4 list-disc space-y-1 pl-6 text-gray-300">
                      {week.goals.map((g: string, i: number) => (
                        <li key={i}>{g}</li>
                      ))}
                    </ul>
                  )}
                <div className="space-y-6">
                  {(week.resources || fallbackResources).map((r: any, i: number) => (
                    <div
                      key={`${r.title}-${i}`}
                      className="flex gap-6 rounded-2xl border border-gray-800 bg-[#111118] p-6"
                    >
                      <div
                        className={`h-32 w-32 rounded-xl bg-gradient-to-br ${
                          i === 0 ? 'from-cyan-500 to-purple-600' : 'from-green-500 to-cyan-500'
                        }`}
                      />
                      <div className="flex-1 space-y-3">
                        <div className="text-sm text-cyan-400">[{r.type}]</div>
                        <h4 className="text-xl font-semibold">{r.title}</h4>
                        <p className="text-gray-400">{r.summary || 'Resource generated by the agent.'}</p>
                        <a className="text-sm text-purple-400" href={r.url}>
                          Show Gemini Summary →
                        </a>
                        <br />
                        <a className="text-sm text-blue-400 underline" href={r.url} target="_blank" rel="noreferrer">
                          {r.url}
                        </a>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
              )
            )}
          </div>

          <Button className="fixed bottom-8 right-8 h-16 w-16 rounded-full bg-purple-600 shadow-2xl hover:bg-purple-500">
            <Pencil className="h-6 w-6" />
          </Button>
        </div>
      </div>
    </div>
  )
}
