import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { CheckCircle2, PlayCircle, BookOpen, Code2, ExternalLink, Cpu, Calendar, Map as MapIcon, Target } from 'lucide-react'

import { Background, PageContainer, SectionHeader, Card, StatPill } from '@/components/shared'
import { fetchRoadmapById } from '@/lib/api'

type RoadmapRow = {
  id: string
  config?: any
  final_roadmap?: any
  selected_strategy?: any
  sandbox_id?: string | null
}

export default function SharedRoadmap() {
  const { id } = useParams<{ id: string }>()
  const [data, setData] = useState<RoadmapRow | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!id) {
      setError('Missing roadmap id in URL.')
      setLoading(false)
      return
    }

    const run = async () => {
      setLoading(true)
      setError(null)
      try {
        const row = await fetchRoadmapById(id)
        setData(row)
      } catch (err: any) {
        setError(err?.message || 'Failed to load roadmap.')
      } finally {
        setLoading(false)
      }
    }

    run()
  }, [id])

  const roadmap = data?.final_roadmap || null
  const config = data?.config || {}
  const selectedStrategy = data?.selected_strategy || {}
  const sandboxId = data?.sandbox_id || null

  const weeks = (roadmap?.weeks as any[]) || []

  const getResourceIcon = (type: string) => {
    const t = (type || '').toLowerCase()
    if (t.includes('video') || t.includes('youtube')) return <PlayCircle className="h-5 w-5 text-red-400" />
    if (t.includes('doc') || t.includes('article')) return <BookOpen className="h-5 w-5 text-blue-400" />
    if (t.includes('project') || t.includes('repo')) return <Code2 className="h-5 w-5 text-purple-400" />
    return <ExternalLink className="h-5 w-5 text-gray-400" />
  }

  if (loading) {
    return (
      <Background>
        <PageContainer maxWidth="6xl">
          <div className="flex min-h-[60vh] items-center justify-center text-slate-300 text-sm">
            Loading shared roadmap…
          </div>
        </PageContainer>
      </Background>
    )
  }

  if (error || !roadmap) {
    return (
      <Background>
        <PageContainer maxWidth="6xl">
          <div className="flex min-h-[60vh] items-center justify-center">
            <div className="rounded-lg border border-red-500/40 bg-red-500/10 px-6 py-4 text-sm text-red-200">
              {error || 'Roadmap not found.'}
            </div>
          </div>
        </PageContainer>
      </Background>
    )
  }

  return (
    <Background>
      <PageContainer maxWidth="6xl" padding="md">
        <div className="mb-3 text-xs text-slate-400">
          Shared Roadmap · ID: <span className="font-mono text-slate-300">{data?.id}</span>
        </div>

        <SectionHeader
          title={roadmap.title || selectedStrategy.name || 'Shared Learning Path'}
          subtitle={
            roadmap.summary ||
            'A curated roadmap shared from PolyPath, generated by agents from the provided learner profile.'
          }
          actions={
            <div className="flex flex-wrap items-center gap-3">
              <StatPill tone="cyan">
                <Calendar className="h-4 w-4" />
                {config.targetWeeks || roadmap.weeks?.length || selectedStrategy.weeks || 4} Weeks
              </StatPill>
              <StatPill tone="purple">
                <Cpu className="h-4 w-4" />
                {config.level || 'Intermediate'}
              </StatPill>
              {sandboxId && (
                <StatPill tone="emerald">
                  Sandbox: {sandboxId}
                </StatPill>
              )}
            </div>
          }
        />

        <div className="mt-4 flex flex-wrap items-center gap-2">
          <StatPill tone="cyan">{config.goalAlignment || 'Skill Acquisition'}</StatPill>
          {config.topic && (
            <StatPill tone="neutral">
              Topic: {config.topic}
            </StatPill>
          )}
        </div>

        <div className="mt-10">
          <div className="mb-4 flex items-center gap-2 text-sm font-semibold tracking-widest text-gray-400 uppercase">
            <MapIcon className="h-4 w-4" /> Curriculum Map
          </div>
          <p className="text-xs text-slate-500">
            This is a read-only view of a roadmap. Share the URL to let others explore the structure.
          </p>
        </div>

        <div className="relative mt-10 space-y-16 pl-4 md:pl-8 before:absolute before:left-2 md:before:left-3 before:top-2 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-cyan-500 before:to-transparent before:opacity-20">
          {(weeks.length ? weeks : Array.from({ length: selectedStrategy?.weeks || 4 }, (_, i) => ({ week: i + 1 }))).map(
            (week: any, idx: number) => (
              <div key={week.week ?? idx} id={`week-${idx + 1}`} className="relative scroll-mt-24">
                <div className="absolute -left-[35px] md:-left-[39px] top-1 flex h-6 w-6 items-center justify-center rounded-full bg-[#0b0f1a] border-2 border-cyan-500/50 shadow-[0_0_10px_rgba(6,182,212,0.5)] z-10">
                  <div className="h-2 w-2 rounded-full bg-cyan-400" />
                </div>

                <div className="mb-8">
                  <h2 className="text-sm font-bold uppercase tracking-widest text-cyan-400 mb-2">
                    Week {week.week || idx + 1}
                  </h2>
                  <h3 className="text-2xl md:text-3xl font-bold text-white">
                    {week.focus || 'Core Concepts & Fundamentals'}
                  </h3>
                </div>

                <div className="grid gap-8 lg:grid-cols-12">
                  <Card className="lg:col-span-4 h-fit">
                    <h4 className="mb-4 flex items-center gap-2 text-sm font-medium text-gray-400 uppercase">
                      <Target className="h-4 w-4" /> Objectives
                    </h4>
                    {week.goals ? (
                      <ul className="space-y-4">
                        {week.goals.map((g: string, i: number) => (
                          <li key={i} className="flex items-start gap-3 text-gray-300">
                            <CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-cyan-500/70" />
                            <span className="text-sm leading-relaxed">{g}</span>
                          </li>
                        ))}
                      </ul>
                    ) : (
                      <p className="text-sm text-gray-500 italic">Objectives loading...</p>
                    )}
                  </Card>

                  <div className="lg:col-span-8">
                    <h4 className="mb-4 text-sm font-medium text-gray-400 uppercase">Recommended Resources</h4>
                    <div className="grid gap-4 sm:grid-cols-2">
                      {(week.resources || []).map((r: any, i: number) => (
                        <Card
                          key={`${r.title}-${i}`}
                          hover
                          padding="md"
                          className="group relative flex flex-col justify-between bg-[#111620]"
                        >
                          <div>
                            <div className="mb-3 flex items-start justify-between">
                              <div className="rounded-lg bg-black/40 p-2.5 transition-colors group-hover:bg-cyan-500/20 group-hover:text-cyan-300 border border-white/5">
                                {getResourceIcon(r.type)}
                              </div>
                              <ExternalLink className="h-4 w-4 text-gray-600 group-hover:text-gray-400" />
                            </div>
                            <div className="mb-2">
                              <span className="inline-block rounded px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wider text-gray-500 bg-white/5 group-hover:text-cyan-400">
                                {r.type}
                              </span>
                            </div>
                            <h5 className="mb-2 text-lg font-semibold text-gray-200 group-hover:text-white line-clamp-2">
                              {r.title}
                            </h5>
                          </div>
                          <p className="text-xs leading-relaxed text-gray-400 line-clamp-2 mt-2">
                            {r.summary || 'AI-curated resource tailored to this roadmap.'}
                          </p>
                        </Card>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            ),
          )}
        </div>
      </PageContainer>
    </Background>
  )
}
